name: Scrape Fortnite Festival

on:
  workflow_dispatch: # Allow manual triggering
  schedule: # Trigger the workflow on a schedule
    - cron: '0 0 * * FRI' # Runs at 00:00 on Fridays (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Define the runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository
      - name: Use Node.js 22  # Define the Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install  # Install dependencies from package.json
      - name: Run the scrape script
        run: node scrapper/scrape.js
      - name: Configure Git user
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[BOT]@users.noreply.github.com'
      - name: Add new files
        run: git add .
      - name: Commit changes
        run: git commit -a -m "Updated Fortnite Festival json file"
      - name: Push changes
        run: git push
